name: Actividades
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  after_layout: ^1.0.7+2
  circular_check_box: ^1.0.2
  cupertino_icons: ^0.1.3
  dotted_border: ^1.0.5
  flutter_file_manager: ^0.2.0
  flutter_launcher_icons: ^0.7.5
  flutter_local_notifications: ^1.3.0
  flutter_markdown: ^0.4.3
  http: ^0.12.2
  path: ^1.7.0
  path_provider: ^1.6.14
  path_provider_ex: ^1.0.1
  rxdart: ^0.24.1
  shared_preferences: ^0.5.8  
  sqflite: ^1.3.1
  introduction_screen: ^1.0.9
  mime_type: ^0.3.2
  share: ^0.6.5
  file_picker: ^1.13.3
  flutter_phoenix: ^0.1.0
  url_launcher: ^5.5.2
  syncfusion_flutter_calendar: ^18.2.56
  timezone: ^0.5.7
  flutter_bloc: ^4.0.0
  dartz: ^0.8.9
  freezed_annotation: ^0.7.1
  get_it: ^3.1.0
  equatable: ^1.1.1
  flutter_list_drag_and_drop: ^0.1.6

dev_dependencies:
  auto_route_generator:
  json_serializable: ^3.3.0
  mockito: ^4.1.1
  lint: ^1.1.1
  build_runner:
  freezed: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-SemiBold.otf
        
  assets:
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
